# Generated by Django 5.1.6 on 2025-02-16 19:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Expired')], default=1)),
                ('activation_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('days_to_activation', models.IntegerField(blank=True, db_index=True, null=True)),
                ('days_since_activation', models.IntegerField(blank=True, db_index=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product')),
            ],
            options={
                'ordering': ['activation_date'],
            },
        ),
    ]
