# Generated by Django 5.1.6 on 2025-02-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Expired')], default=1)),
                ('activation_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('days_to_activation', models.IntegerField(blank=True, db_index=True, null=True)),
                ('days_since_activation', models.IntegerField(blank=True, db_index=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
