name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Fly.io CLI y configurar PATH
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH  # Agrega Fly.io al PATH

      - name: Verificar instalación de Fly.io
        run: flyctl version

      - name: Autenticarse en Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy en Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }} flyctl deploy --remote-only