name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Se ejecutará cuando hagas push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy en Fly.io
        run: flyctl deploy --remote-only