name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Se ejecutar치 cuando hagas push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Usa la misma versi칩n de Python de tu proyecto

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar collectstatic
        run: |
          python manage.py collectstatic --noinput --verbosity 3
        env:
          DJANGO_SETTINGS_MODULE: "tu_proyecto.settings"
          DEBUG: "False"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}


      - name: Instalar Fly.io CLI y configurar PATH
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH  # Agrega Fly.io al PATH

      - name: Verificar instalaci칩n de Fly.io
        run: flyctl version

      - name: Autenticarse en Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth token ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy en Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }} flyctl deploy --remote-only